### ISSUE TITLE
Import map data into in-app database

### ISSUE THREAD

**Issue by Istrali** [5donuts/mapper#12]
- [x] #15 Database queries needed
- [x] #19 Parsing the json file
- [x] #11 Complete the json file
- [x] #35 Update the database schema
- [x] #39 Rework the JSON file to match the changed database schema
