### ISSUE TITLE
Add Basic Navigation

### ISSUE THREAD

**Issue by 5donuts** [5donuts/mapper#18]
Tasks:
- [x] #12 add map data to the in-app database
- [x] #9 create a basic graph structure in memory
- [x] #10 implement Dijkstra's shortest path algorithm using that graph structure
- [x] #14 show the path of `PolyLine`s selected by Dijkstra's
